name: "\U0001F41B Сообщение об ошибке"
description: Сообщите об ошибке, чтобы улучшить работу GigaChain. Для обратной связи о проблемах с безопасностью воспользуйтесь отдельной формой ниже.
labels: ["02 Сообщение об ошибке"]
body:
  - type: markdown
    attributes:
      value: >

        Перед тем как сообщить об ошибке, пожалуйста, убедитесь, что вашей проблемы нет среди открытых issue.

        Разработчики стараются своевременно обрабатывать все открытые issue. Тем не менее, если вы считаете, что обнаруженную ошибку нужно рассмотреть с повышенным приоритетом, вы можете уведомить об этом руководителя проекта — @Rai220.
  - type: textarea
    id: reproduction
    validations:
      required: true
    attributes:
      label: Воспроизведение ошибки
      description: |
        Предоставьте [образец кода](https://stackoverflow.com/help/minimal-reproducible-example), при выполнении которого возникает ошибка. Подойдет как ссылка на Colab, так и отдельный фрагмент кода.
        По возможности, приложите другие примеры кода, сообщения об ошибках и стек трейсы, которые помогут воспроизвести проблему.

        Обратите внимание на корректное [выделение блоков кода с помощью тегов](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#syntax-highlighting).

        Не нужно присылать скриншоты кода. Такие примеры неудобно читать и их нельзя скопировать.
      placeholder: |
        from langgraph.graph import StateGraph

        def bad_code(inputs) -> int:
          raise NotImplementedError('For demo purpose')
          
        chain = StateGraph(list)
        chain.invoke('Hello!')
      render: python
  - type: textarea
    id: error
    validations:
      required: false
    attributes:
      label: Сообщение об ошибке и трассировка стека (если применимо)
      description: |
        Если вы хотите сообщить об ощибке, пожалуйста, приложите полное сообщение и трассировку стека.
      placeholder: |
        Exception + полная трассировка стека
      render: shell
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: |
        Напишите короткое описание того, что вы делаете, какое поведение наблюдаете и какого поведения ожидали.
      placeholder: |
        * Я пытаюсь использовать `gigachain` чтобы сделать X.
        * Я ожидаю получить Y.
        * Вместо этого происходит Z.
    validations:
      required: true
  - type: textarea
    id: system-info
    attributes:
      label: Системная информация
      description: |
        Пожалуйста, поделитесь данными о вашем окружении

        "pip freeze | grep gigachain" 
        ОС (windows / linux / mac)
        python version

        Если вы используете последние версии gigachain-core, приведите резултат вызова команды:

        python -m gigachain_core.sys_info
      placeholder: |
        "pip freeze | grep langchain"
        OC
        python version

        Если вы используете последние версии gigachain-core, приведите результат вызова команды:

        python -m langchain_core.sys_info

        Команда возвращает пакеты, которые использует GigaChain. При необходимости укажите другие релевантные пакеты.
        Если вы не уверены в том, какие пакеты стоит указывать, можете приложить весь результат команды `pip freeze`.
    validations:
      required: true
