blank_issues_enabled: false
contact_links:
  - name: 🤔 Вопрос или проблема
    about: Задайте вопрос или расскажите о проблеме
    url: https://www.github.com/ai-forever/gigagraph/discussions/categories/q-a
  - name: Запрос на доработку
    url: https://www.github.com/ai-forever/gigagraph/discussions/categories/ideas
    about: Поделитесь идеей или предложите доработку
  - name: Ваши истории
    about: Расскажите как вы использовали GigaGraph для решения своих задач
    url: https://www.github.com/ai-forever/gigagraph/discussions/categories/show-and-tell
