blank_issues_enabled: false
version: 2.1
contact_links:
  - name: 🤔 Вопрос или проблема
    about: Задайте вопрос или расскажите о проблеме
    url: https://www.github.com/langchain-ai/langchain/discussions/categories/q-a
  - name: Запрос на доработку
    url: https://www.github.com/ai-forever/gigachain/discussions/categories/ideas
    about: Поделитесь идеей или предложите доработку
  - name: Ваши истории
    about: Расскажите, как вы использовали GigaChain для решения своих задач
    url: https://www.github.com/langchain-ai/langchain/discussions/categories/show-and-tell
