name: Документация
description: Расскажите как мы можем улучшить документацию GigaChain.
title: "DOC: <Укажите развернутый заголовок после префикса 'DOC: '>"
labels: [03 - Документация]

body:
- type: markdown
  attributes:
    value: >
      Благодарим вас за пощь в развитии документации GigaChain.
- type: checkboxes
  id: checks
  attributes:
    label: Контрольный список
    description: Убедитесь, что при создании issue выполнены все пункты контрольного списка.
    options:
      - label: Добавлен исчерпывающий заголовок.
        required: true
      - label: Приложена ссылка на страницу, на которой обнаружена проблема (если применимо).
        required: true
- type: textarea
  attributes: 
    label: "Проблема с существующей документацией:"
    description: >
      Оставьте ссылку на страницу документации или файл кода, где, по вашему мнению, нужно доработать документацию.

- type: textarea
  attributes:
    label: "Запрос на доработку:"
    description: >
      По возможности подробнее опишите какие темы следует отразить в существующей документации, по вашему мнению.